### ISSUE TITLE
Pod Linking issue 

### ISSUE THREAD

**Issue by sabih3** [apptentive/apptentive-react-native#139]
Hi there

When I am trying to run pod install, I am getting the following error:

CocoaPods could not find compatible versions for pod "apptentive-ios":
  In Podfile:
    apptentive-ios

    apptentive-react-native (from `../node_modules/apptentive-react-native`) was resolved to 5.6.1, which depends on
      apptentive-ios (< 6.0, >= 5.3.1)

Specs satisfying the `apptentive-ios, apptentive-ios (< 6.0, >= 5.3.1)` dependency were found, but they required a higher minimum deployment target.

The project's min deployment target is ios 10.0
Version resolved by package manager for apptentive-react-native is  5.6.1

Can anyone please check and advise.

Thanks

**Comment by CaseyApptentive** [comment]
Hi @sabih3. Happy to help. Let me dig into this with my team. 

I saw that you also reached out to support@apptentive.com -- which is great. We'll reply to you in that thread, but also post the solution here once we know for certain.

**Comment by sabih3** [comment]
Hey @CaseyApptentive . I upgraded iOS minimum targeting to 11.0 & it's working now.

If you guys can just mention this in docs, it may be helpful for other devs as well. 

Thanks
