### ISSUE TITLE
How close to release is package

### ISSUE THREAD

**Issue by nagad814** [apptentive/apptentive-react-native#14]
Hi, I am looking at integrating your sdk into my React native app. would like to know how close are you to a release build. PS: I see your develop branch has lot of progress already.

**Comment by nagad814** [comment]
Also we are looking at IOS release first.

**Comment by weeeBox** [comment]
Hey @nagad814,

We are targeting the end of this week or early next week. Stay tuned!

**Comment by nagad814** [comment]
thank you

**Comment by weeeBox** [comment]
Hey @nagad814,

Apptentive package is now available on `npm`:
https://www.npmjs.com/package/apptentive-react-native
