### ISSUE TITLE
Warning of not being initialized, while initializing

### ISSUE THREAD

**Issue by TomSwift** [apptentive/apptentive-react-native#169]
The first call we make in JS to Apptentive is `Apptentive.register()`, passing the configuration object.   It's annoying that in making this call the following is written to the console:

```W/Apptentive: Apptentive instance is not initialized. Make sure you've registered it with your app key and signature.```

I mean, we're in the process of registering here, passing both the app key and signature..

Version 5.3.4.

**Comment by CaseyApptentive** [comment]
@TomSwift, sorry for the long delay. I wanted to circle back as we clean out our backlog. This should not be an issue on more recent versions of the SDK. Could you try using the latest 6.0.2?

Again, very sorry for the gap in communication. 

Closing this for now but let me know if it's still an issue.
