### ISSUE TITLE
App crashes on android (only) when register method is called. v5.8.3 and v.6.0.0

### ISSUE THREAD

**Issue by michaelmontero** [apptentive/apptentive-react-native#194]
I receive the follow error occurs when `register` method is called in android (only). 

Attempt to invoke with virtual method `'boolean.com.facebook.react.uimanager.FabricViewStateManager.hasStateWrapper()' on a null object reference.` 

No error in the console.
```
Apptentive.register(configuration).catch((error) => { 
      console.log('Unable to initialize apptentive', error);
});
```

React Native version: 0.66.4
compileSdkVersion: 31

**Comment by frankus** [comment]
Thank you for the report!

Could you let us know whether this a new app or is an existing app that you updated to version 6 of the `apptentive-react-native` package?

**Comment by michaelmontero** [comment]
@frankus its an existing app. We were using successfully version 5.7.3.

**Comment by HarryAWoodworth** [comment]
@michaelmontero is this app built using React Native Expo?

**Comment by michaelmontero** [comment]
No @HarryAWoodworth

**Comment by frankus** [comment]
Our 5.8.0 Android SDK updated the appCompat dependency to version 1.3.1. 

Can you try adding the following to the `dependencies` section of `android/app/build.gradle`?:

```
implementation ("androidx.appcompat:appcompat:1.3.1") {
    version {
        strictly '1.3.1'
    }
}
```

**Comment by michaelmontero** [comment]
works @frankus
