### ISSUE TITLE
Override/Set Message Center background color

### ISSUE THREAD

**Issue by cristianbriscaru** [apptentive/apptentive-react-native#200]
Hi, I am using this library with Expo (managed) and the background color for the Message Center is a dark blue , how can I override /set the background  color ?

**Comment by frankus** [comment]
Android and iOS have different methods of setting colors. Are you seeing this in Android, iOS, or both?

**Comment by cristianbriscaru** [comment]
Hi @frankus , I am seeing this on Android, haven't checked on iOS yet

**Comment by PoornimaApptentive** [comment]
@cristianbriscaru Check out the _MessageCenter_ section under _What Styles We Use_ in our [learn doc](https://learn.apptentive.com/knowledge-base/android-interface-customization/). We use `colroBackground` to set the MessageCenter background color. You can override the default theme in your `styles.xml`
<style name="ApptentiveThemeOverride">
  <item name="colorPrimary">#FFEB3B</item>
  <item name="colorPrimaryDark">#FDD835</item>
  <item name="colorBackground">#FFFFFF</item>
  <item name="apptentiveCardBorderColor">#757575</item>
</style>

**Comment by cristianbriscaru** [comment]
I am using Expo managed (with EAS custom dev client) so I don't have any android styles.xml, will have a look how I can achieve this without ejecting.
