### ISSUE TITLE
Apptentive doesn't start on Android 13 before notification permissions are set.

### ISSUE THREAD

**Issue by ieatfood** [apptentive/apptentive-react-native#204]
In Android 13 apps have to request notification permission at runtime, like on iOS.

If an app is launched without having the notification permissions allowed or disallowed (neither set, the prompt shows), Apptentive won’t start with this error in logcat: `Exception while initialized Apptentive`.

After permission is granted or denied, next time the app starts Apptentive starts normally.

https://developer.android.com/about/versions/13/changes/notification-permission

**Comment by CaseyApptentive** [comment]
Hi @ieatfood, thanks for reaching out. I've shared this with my team and will follow up with you as soon as possible.

**Comment by CaseyApptentive** [comment]
Hi @ieatfood, thanks for the report. I'm looking into this issue with my team and will follow up with you as soon as possible.

**Comment by CaseyApptentive** [comment]
Hi @ieatfood, thanks again for the report. We're having trouble reproducing the issue. 

Are you seeing this issue every time? Are you testing on a dev app or in production?

Any additional details that could help us repro the problem would be great.

**Comment by CaseyApptentive** [comment]
Thanks again for reaching out. Our team has continued testing Android 13 but we're still having trouble reproducing this issue. There have been no major red flags that we have identified at the time, though we continue to test more intensely to uncover any possible issues. 

Let me know if there are any further details you can share so that we can repro the issue. 

If easier, you could also share a dev app with us (e.g. via APK) to casey@apptentive.com and then we can help do some of the testing for you.

**Comment by CaseyApptentive** [comment]
@ieatfood, following up. We still have not been able to reproduce this issue. 

Are you still seeing this problem? If so, can you tell us more so we can repro the problem?

Thanks again for the report. Let me know if this is still an issue for you!

**Comment by CaseyApptentive** [comment]
Hi @ieatfood. My team has dug in, believe they have an understanding of the issue, but are still having trouble reproducing it. They'll continue to look into it, but they wanted me to mention that, if you request the push notification on app startup (vs. waiting for Apptentive to request it), this should solve the problem.

Could you give that a try? Will that free you up for the time being? 

Thanks!

**Comment by CaseyApptentive** [comment]
@ieatfood let us know if this is still an issue for you. We haven't heard other reports and are happy to dig in further, but closing for now.
