### ISSUE TITLE
Post install script not working

### ISSUE THREAD

**Issue by nagad814** [apptentive/apptentive-react-native#21]
Here is my final post install script in Pod file.
getting Appentive.h missing error. 
Please help

`post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_OBJC_WEAK'] ||= 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.3'
            unless installer.podfile.defined_in_file.read().include? "\nuse_frameworks!\n"
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NO_USE_FRAMEWORKS=1'
            end
        end
        if target.name == "React"
            target.remove_from_project
        end
    end
end`

**Comment by weeeBox** [comment]
Hi @nagad814,

Sorry for the issue. We're looking at it right now.

**Comment by nagad814** [comment]
thank you

**Comment by nagad814** [comment]
I think your podsec file needs react as dependency `s.dependency 'React/Core'`

**Comment by frankus** [comment]
I've been working on reproducing this issue, but for me the post-install hook seems to be working reliably. 

I created a test React Native app and added the following Podfile to the ios directory:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTest
  pod 'apptentive-ios', '5.0.3'
end
```

After running `pod install` I can reproduce the issue (complaining about missing Apptentive.h file). 

I then added the following post-install hook at the top level of the Podfile (immediately below the above snippet):

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_OBJC_WEAK'] ||= 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.3'
            unless installer.podfile.defined_in_file.read().include? "\nuse_frameworks!\n"
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NO_USE_FRAMEWORKS=1'
            end
        end
        if target.name == "React"
            target.remove_from_project
        end
    end
end
```

After re-running `pod install` and re-building the app, it builds as it is supposed to. 

We have experimented with adding the `React/Core` dependency but that pod is deprecated and didn't appear to be necessary to build the project. 

Can you let us know if there is anything else we can try to get the issue reproduced?

Thanks!

**Comment by nagad814** [comment]
Hi, I was able to resolve my issue by changing the Apptentive_Private.h, import statement to 

`#import "Apptentive.h"` 

https://github.com/nagad814/apptentive-ios/blob/master/Apptentive/Apptentive/Apptentive_Private.h
