### ISSUE TITLE
iOS error: illegal callback invocation from native module. This callback type only permits a single invocation from native code."

### ISSUE THREAD

**Issue by und3f1n3d** [apptentive/apptentive-react-native#214]
I am getting this error screen on App Launch in simulator

![Screen Shot 2023-01-13 at 2 21 32 PM](https://user-images.githubusercontent.com/6744400/212409368-9116fc4e-084d-4552-b467-6e3c6bedf71a.png)

On reload, this error is gone.  When I comment out `Apptentive.register(configuration)`, I dont' get this error screen anymore. 

System info:
Ran on iOS Simulator IPhone 13 with iOS 15.5, still using the old react native architecture, and xcode 13
The error does not show on iOS device.
Using the following packages with Node 16 and NPM 9.x
```
    "apptentive-react-native": "6.0.3",
   "react-native": "0.70.6",
    "react": "18.2.0",
```

Please help. Thank you.

**Comment by galengeocaching** [comment]
I had been experiencing this error on version 6.0.3, but after updating to 6.0.9 and updating the ApptentiveKit pod I am no longer seeing it.

**Comment by und3f1n3d** [comment]
yep i am not seeing this anymore. thank you .
