### ISSUE TITLE
Upgrade from 6.0.2 to 6.1.2 causing issues with Apptentive Theme Override properties in Android

### ISSUE THREAD

**Issue by ardentcricket** [apptentive/apptentive-react-native#236]
Hello, after upgrading from 6.0.2 to 6.1.2 we are facing issues with the following properties 
`apptentiveCardBorderColor` and `apptentiveCardBackground` in Android.

Error:
`AAPT: error: style attribute 'attr/apptentiveCardBorderColor not found`
`AAPT: error: style attribute 'attr/apptentiveCardBackground not found`

```
  <item name="apptentiveCardBorderColor">#FFFFFF</item>
  <item name="apptentiveCardBackground">#333</item>
```

**Comment by ChaseApptentive** [comment]
Hi @ardentcricket ,

Sorry about the delay. Looks like you may have figured out the issue.

Our new SDK (`apptentive-kit-android`) which is version 6+ has completely revamped the UI as well as the styling and [deprecated and replaced our old styles](https://learn.apptentive.com/knowledge-base/android-interface-customization-2/#deprecated-styles). 

`apptentiveCardBorderColor` and `apptentiveCardBackground` no longer exist in the new version of the SDK. The equivalent might be to create a drawable with a border and a background and set it to the `android:background` element for the Survey questions and Message Center bubbles.

However, I'd suggest trying the default stylings (just remove all old apptentive stylings) and see how that looks for your app. We have tried to integrate the host app's theme colors into our interactions wherever possible. More guidance on that [here](https://learn.apptentive.com/knowledge-base/android-interface-customization-2/#important-styles-we-inherit).

[Here](https://learn.apptentive.com/knowledge-base/android-interface-customization-2/) is our new interface customization guide that has all our current styles.

Hope this helps!
