### ISSUE TITLE
App crashes when showing message center on android

### ISSUE THREAD

**Issue by luistarz** [apptentive/apptentive-react-native#24]
I have integrated `apptentive-react-native` library into my react native app but when i try to call `Apptentive.presentMessageCenter()` function, the android app crashes without giving error details.
I tried to call `canShowMessageCenter` method and it returned `true` so I guess the problem is in presenting logic.

My env:
```
react-native: 0.55.3
apptentive-react-native: 5.1.0
```

Anybody can help on this?

**Comment by weeeBox** [comment]
Hey @luistarz,

Sorry for the late response. We're looking at it right now.

**Comment by weeeBox** [comment]
Hi @luistarz,

Would you be able to provide your `package.json`?

**Comment by msaffitz** [comment]
Hi @luistarz ; we're going to close this ticket as we've not heard back from you.  Please feel free to reopen it or reach out to support@apptentive.com if you're still having this issue.
