### ISSUE TITLE
Messaging Center on android not appearing

### ISSUE THREAD

**Issue by jebzaki** [apptentive/apptentive-react-native#35]
Works great on iOS, I'm using apptentive-react-native 5.1.4 and react native 0.51. I'm also using react-native-router-flux 3.43.0 to handle my scenes/routes.

```
Apptentive.presentMessageCenter()
    .then(presented => {
        if (!presented) {
            console.warn("Message Center", "Message Center was not presented")
        }

        console.warn(presented)
    })
    .catch(error => {
        console.warn("Message Center", `Error while presenting Message Center:\n\n${error.message}`)
    }),
```

'presented' returns true, however it still doesn't show.

**Comment by weeeBox** [comment]
Hi @jebzaki,

Sorry for the issue. We'll take a look at it asap.

**Comment by weeeBox** [comment]
Hi @jebzaki,

Would you be able to collect device logs and share them with us? You can enable `verbose` logging by passing it with a configuration object while registering Apptentive.

```
const configuration = new ApptentiveConfiguration(
  <YOUR_APP_KEY>,
  <YOUR_APP_SIGNATURE>
);
configuration.logLevel = 'verbose';
Apptentive.register(configuration)
  .then(() => {
    ...  
  })
  .catch((error) => {
    ...
  });
``

**Comment by jebzaki** [comment]
I did as asked using this debug key
```
com.apptentive.debug:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ0eXBlIjoiZGVidWciLCJpc3MiOiJhcHB0ZW50aXZlIiwic3ViIjoiNWI3MWNiZTdkYTY2OTkwM2E4MDAwMGJiIiwiYXBwX2lkIjoiNWI3MWNiZTdkYTY2OTkwM2E4MDAwMGJiIiwiZXhwIjoxNTM2MzQ3OTU4LCJpYXQiOjE1MzYyNjE1NTgsInJlY2lwaWVudHMiOlsibG9nc0BhcHB0ZW50aXZlLmNvbSJdLCJsZXZlbCI6IlZFUllfVkVSQk9TRSIsImZpbHRlcl9hcHBfcHJvY2VzcyI6dHJ1ZX0.l4ktiX8b4JKHDbXkd0TJYsLJ1zAIRqL0uFwCXToqO8b9zQ3jfZqfFd_xoHXds2jk_HHC5KfB7peWhVB_CsMjEQ
```

Unfortunately when I try to send report nothing happens. (This is using an android emulator by the way)

**Comment by weeeBox** [comment]
Can you pass the `verbose` log level along with configuration object?

**Comment by jebzaki** [comment]
I'm not sure what you want me to do. 
I'm not sure how to access any logs that might be stored locally if that's what you're referring to.

**Comment by jebzaki** [comment]
Yes I have added that to my configuration object as you asked. 

Then I copied my debug key within the device and launched the app. 
I followed the instructions given on the notification and attempted to open the message center within the app. When I attempt to send the report or dismiss nothing happens.

**Comment by weeeBox** [comment]
You can get logs using this command line:
`adb logcat -s Apptentive`

**Comment by weeeBox** [comment]
Looks like `com.apptentive.android.sdk.ApptentiveViewActivity` was not added to the manifest while merging. As a workaround, you can add it manually.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.apptentive.android.sdk">
    ...
    <application>
        ...
        <activity android:name="com.apptentive.android.sdk.ApptentiveViewActivity"
                  android:theme="@style/ApptentiveTheme.Base.Versioned"/>
    </application>
</manifest>
```

**Comment by jebzaki** [comment]
Works great! I just have to change the theme color and it's good. 

Thank you.

**Comment by weeeBox** [comment]
Awesome!
