### ISSUE TITLE
Can apptentive-react-native support all the native feature?

### ISSUE THREAD

**Issue by pengcao1** [apptentive/apptentive-react-native#42]
Hi guys：

we try to use apptentive make rating/surveys/ etc.
and does this `apptentive-react-native` full support as native(android/ios sdk?)

Thanks

**Comment by weeeBox** [comment]
Hey @pengcao1,

We support most of the native API. Which calls are you missing?

**Comment by weeeBox** [comment]
Hi @pengcao1,

Ratings and surveys are already supported on both platforms. Push notifications should be configured in the native projects. Please, follow [this](https://github.com/apptentive/apptentive-react-native#push-notifications) guide. Let me know if you have any questions.

**Comment by weeeBox** [comment]
Hi @pengcao1,

Did it solve your issue?

**Comment by frankus** [comment]
Closing for now. Please reopen if this is still an issue.
