### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by JakeRawr** [apptentive/apptentive-react-native#76]
Hi, 

Does the latest version support React-Native@0.60 with AndroidX?

**Comment by weeeBox** [comment]
Hey @JakeRawr, the SDK use support library 28 as a dependency. Are you facing any issues rn?

**Comment by darran-kelinske-fivestars** [comment]
I just tried the latest version `    "apptentive-react-native": "5.4.3",` and it doesn't appear to work with AndroidX

**Comment by darran-kelinske-fivestars** [comment]
Is anyone working on adding androidx support?

**Comment by CaseyApptentive** [comment]
Hi @darran-kelinske-fivestars. Let me sync with my team to get a confirmation. Stay tuned!

**Comment by CaseyApptentive** [comment]
@darran-kelinske-fivestars can you tell me more about the type of issues you're having? We should be able to work with AndroidX but we need to make sure the libraries are compatible. 

Any logs or screenshots would be appreciated!

**Comment by darran-kelinske-fivestars** [comment]
We ended up removing the library. In short, you need to migrate your dependencies to AndroidX if you'd like to support the latest versions of react native.

**Comment by CaseyApptentive** [comment]
Thanks for the update. We're looking into compatability. I'll let you know as soon as I have an update. 

Apologies for the low level questions, but to confirm: it sounds like you removed Apptentive from your Android app until we have a solution? 

I want to be sure we're prioritizing this work appropriately.

**Comment by darran-kelinske-fivestars** [comment]
correct - we removed it from android and react native

**Comment by CaseyApptentive** [comment]
Thanks for clarifying @darran-kelinske-fivestars . Working with my team to investigate this right now. 

I'll keep you posted on any updates.

**Comment by CaseyApptentive** [comment]
@darran-kelinske-fivestars,

Circling back with this. We've tested more with React Native (version 0.61.2) and our latest RN SDK (5.4.3 which has been migrated to AndroidX) and are unable to reproduce the issue you saw. We'll need a bit more info. 

We built a new react native project with the following dependencies and successfully integrated the Apptentive SDK with it

"dependencies": {

"apptentive-react-native": "^5.4.3",

"react": "16.9.0",

"react-native": "0.61.2"

}

We were able to build the app and even testing Apptentive features within it, like Message Center, worked in our tests. 

Can you show us what you're seeing so we can dig in? Any error logs or steps to repro would be great. 

Also can you send us your package.json from the project?

Thanks!

**Comment by CaseyApptentive** [comment]
@darran-kelinske-fivestars 

Circling back. Are you still having issues? 

If so, can you send your package.json, logs, and steps to repro (if possible)?

Thanks!

**Comment by darran-kelinske-fivestars** [comment]
idk - it might still be an issue, but we removed the sdk for now - would
ask the other poster

**Comment by CaseyApptentive** [comment]
@JakeRawr are you still having issues? If so, can you send your package.json, logs, and steps to repro (if possible)?

**Comment by twinklesharma1311** [comment]
@JakeRawr  are you still facing issues? If so, we would really appreciate if you can send your package.json, logs, and steps to repro (if possible)?

**Comment by JakeRawr** [comment]
Hi @twinklesharma1311 @CaseyApptentive 

We successfully rolled out apptentive with react-native 0.60+ on both iOS and Android a couple weeks ago. Everything seems to be working and feel free to close this.

**Comment by twinklesharma1311** [comment]
Thanks for the update @JakeRawr

**Comment by CaseyApptentive** [comment]
@darran-kelinske-fivestars: wanted to circle back with you as well. 

We have a fix that's live in v5.4.6. Let me know if you have any questions along the way. 

https://github.com/apptentive/apptentive-react-native/releases/tag/v5.4.6

**Comment by CaseyApptentive** [comment]
@darran-kelinske-fivestars, we have a fix out specific to AndroidX for React Native 0.60+. Can you upgrade to SDK v5.5.0?

https://github.com/apptentive/apptentive-react-native/releases/tag/v5.5.0

Thanks again!
