### ISSUE TITLE
React native callback for unread messages not working

### ISSUE THREAD

**Issue by bpfeiffer187** [apptentive/apptentive-react-native#79]
I have tried to use the call this:
Apptentive.onUnreadMessageCountChanged = (count) => {
      console.log(`render:${count}`);
      alert('count = ' + count);
    };

the call back only works while I have the message window open. I am missing something?

**Comment by CaseyApptentive** [comment]
Thanks for reaching out @bpfeiffer187 ! Let me take a closer look with my engineers.

**Comment by bpfeiffer187** [comment]
I found that the data was just time delayed.
