### ISSUE TITLE
React Native 0.60+ and autolinking

### ISSUE THREAD

**Issue by jpr-longgame** [apptentive/apptentive-react-native#80]
Using RN 0.60-style autolinking seems to be broken.

Launching the app, on calling `Apptentive.register`, we get "Native module cannot be null".

Following the manual install instructions, the app doesn't build - missing React dependency (since React is built as part of the Pods project).

eta: Dependencies include these:

"apptentive-react-native": "^5.4.3",

"react": "16.9.0",

"react-native": "0.61.2"

`ios/Podfile` includes these:

pod 'apptentive-ios'

pod 'Apptentive', :path => '../node_modules/apptentive-react-native'

**Comment by bpfeiffer187** [comment]
I am also having the same issue with RN .61.

Manual linking the app fails to build with error:
Pod Error:
Pod installation complete! There are 40 dependencies from the Podfile and 38 total pods installed.
 
[!] use_native_modules! skipped the react-native dependency 'apptentive-react-native'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library


Run Error:
Error:
 
Lexical or Preprocessor Issue Group
/Users/a14226/newappworkspace/amica-mobile-web/node_modules/apptentive-react-native/ios/RNApptentiveModule.h:5:9: 'React/RCTEventEmitter.h' file not found
/Users/a14226/newappworkspace/amica-mobile-web/node_modules/apptentive-react-native/ios/RNApptentiveModule.m:1:9: In file included from /Users/a14226/newappworkspace/amica-mobile-web/node_modules/apptentive-react-native/ios/RNApptentiveModule.m:1:

**Comment by CaseyApptentive** [comment]
Thanks for the reports, @bpfeiffer187  and @jpr-longgame! We're looking into this. Stay tuned for next steps. 

Appreciate your patience as we dig in.

**Comment by jpr-longgame** [comment]
@bpfeiffer187 you can get around your issue by placing a file named Apptentive.podspec in node_modules/apptentive-react-native:

```
require 'json'
pjson = JSON.parse(File.read('package.json'))

Pod::Spec.new do |s|

  s.name            = "Apptentive"
  s.version         = pjson["version"]
  s.homepage        = "https://www.npmjs.com/package/react-native-apptentive-module"
  s.summary         = pjson["description"]
  s.license         = pjson["license"]
  s.author          = { "Apptentive" => "support@apptentive.com" }
  
  s.ios.deployment_target = '8.0'
  s.tvos.deployment_target = '9.2'

  s.source          = { :git => "https://github.com/apptentive/apptentive-react-native.git" } 
  s.source_files    = '*.{h,m}'
  s.preserve_paths  = "**/*.js"

  s.dependency 'React'
end
```

**Comment by Zeneixe** [comment]
We have the same issue, any updates?

**Comment by frankus** [comment]
Please take a look at the SEA-1402 branch to see if that fixes the problem you're running into.

**Comment by jpr-longgame** [comment]
@frankus I don't see a SEA-1402 branch, I may be missing something though?

**Comment by frankus** [comment]
Sorry @jpr-longgame, I merged the changes into the `develop` branch this morning. We're doing a run-through of our sample project and after that we'll cut an official release.

**Comment by frankus** [comment]
We just released version 5.4.5 which should address this. Please let us know if it works for you!

**Comment by bpfeiffer187** [comment]
@frankus thanks going to install it today. Just to be clear this doesn't full support auto linking correct? this just fixes the podspec file for when we link manual?

**Comment by frankus** [comment]
I made a bit of a rookie mistake with the 5.4.5 release and forgot to include the `podspec` file in the `package.json`. So you'll want the 5.4.6 release. 

I was able to create a new RN project, install this module, and run `pod install` in the `ios` directory, and everything linked correctly.

**Comment by frankus** [comment]
Sorry, I didn't really address your question directly, @bpfeiffer187. You should be able to just switch to the `ios` directory (after installing the `apptentive-react-native` module) and run `pod install`. No further linking needed. 

I'm going to close this for now but let us know if this is still an issue for you.
