### ISSUE TITLE
Apptentive podspec file specifies older version of the SDK

### ISSUE THREAD

**Issue by shercoder** [apptentive/apptentive-react-native#93]
https://github.com/apptentive/apptentive-react-native/blob/master/apptentive-react-native.podspec#L3 specifies `5.4.4` but the release notes say the podspec wasn't supported until `5.4.5`.

Also are there updated docs, do we still have to specify `apptentive-ios` in our Podfile or since the podspec file specifies it, `pod install` will install it automatically?

**Comment by CaseyApptentive** [comment]
Thanks for reaching out @shercoder. We'll get back to you with next steps as soon as possible. 

In the meantime, could you email us directly at support@apptentive.com with details on which app you're working on? I want to be sure we're looping in your appropriate Customer Success Manager as we work on a fix.

**Comment by frankus** [comment]
We've just fixed this in the 5.4.6 release, and updated our release process to automatically keep it up to date. We also fixed a bug where the `podspec` file was not included in the `package.json` file. Finally, we've updated the documentation (please look at the `master` branch for this) to reflect the new, much simpler installation process.

**Comment by shercoder** [comment]
@frankus @CaseyApptentive So are we not suppose to specify `pod 'apptentive-ios', '5.2.7'` in our Podfile?

Instructions on your official page says we should but master branch docs don't specify it https://learn.apptentive.com/knowledge-base/react-native-integration-reference/

And no linking required for Android either?

**Comment by shercoder** [comment]
Just an FYI for anyone else visiting here:
I am using React Native 0.59.10 so in order to integrate `apptentive-react-native` use the following steps:

1. First of all make sure you unlink previous lib via `react-native unlink apptentive`
    1. discard the unlinking for Android files because that does not change. Although I noticed that `apptentive-react-native@5.4.6` installs Apptentive Android SDK version `5.4.0` instead of the specified version in the release, i.e. `5.4.7`. Not sure how to update this.
2. Then install latest: `npm install apptentive-react-native@5.4.6 --save-exact`
3. Open your Podfile and add these two lines:
    1. `pod 'apptentive-ios', '5.2.7'`
    2. `pod 'apptentive-react-native', :podspec => '../node_modules/apptentive-react-native'`
4. `cd ios ; pod install`

**Comment by shercoder** [comment]
ah looks like the the Android SDK version was never updated to 5.4.7 in your gradle file https://github.com/apptentive/apptentive-react-native/blob/master/android/build.gradle#L35

**Comment by shercoder** [comment]
I fixed the android issue by adding this to our top-level `build.gradle`:
```
allprojects {
    repositories {
        configurations.all {
            resolutionStrategy {
                force 'com.apptentive:apptentive-android:5.4.7'
            }
        }
    }
}
```
